### PR TITLE
[GSoD 2021] Formatted .vscode files using prettier

### PR DESCRIPTION
**Pull request by iamrajiv**
Related: wechaty/docusaurus#1012

### CODE REVIEW

**Comment by iamrajiv** [comment]
@huan @proudofsimin @Rohitesh-Kumar-Jain Please take a look.

**Review by Rohitesh-Kumar-Jain — APPROVED** [review]
Pure refactoring

**Comment by iamrajiv** [comment]
@proudofsimin plz take look

**Comment by huan** [comment]
Hi @iamrajiv ,

Thanks for introducing the `prettier to our project!

After I learn about it, I think it would be great if we can have a prettier linter in our community.

Could you please read the https://prettier.io/docs/en/integrating-with-linters.html and propose a solution? For example, we can add the prettier linting plugin to `@chatie/eslint-config`, so that all the Wechaty community projects can be benefited from it.

**Comment by iamrajiv** [comment]
@huan Yeah I was going through Prettier setup for the Wechaty projects. This might help https://github.com/creyD/prettier_action. This action format files according to Prettier whenever there is a PR and push to the repository.

**Comment by huan** [comment]
I think what we need is a linter which will throw an error by following our config file, instead of a rewriter.

For this PR, it will be good to go after:

1. Follow my review: always keep the trailing comma, and
2. Make the CI green by fixing the code.

Thank you very much!

**Comment by huan** [comment]
Link to:

- https://github.com/Chatie/eslint-config/issues/82

**Pull request closed without merging**
