### PR TITLE
[GSoD 2021] Added Swagger UI to Express Route by default

### LINKED ISSUE #4: Added Swagger UI to Express Route by default
We can copy <https://github.com/johanbrandhorst/grpc-gateway-boilerplate/tree/master/third_party/OpenAPI>

### PR DESCRIPTION
**Pull request by iamrajiv**
Fixes: #4
Related: wechaty/docusaurus#1012

Screenshot 2021-06-26 at 6 16 20 AM

### CODE REVIEW

**Comment by iamrajiv** [comment]
@huan @proudofsimin @Rohitesh-Kumar-Jain Please take a look.

**Review by proudofsimin — APPROVED** [review]
Not so familiar with web but seems ok to me.

**Review by Rohitesh-Kumar-Jain — APPROVED** [review]
This should be looked upon by a code maintainer

**Comment by lijiarui** [comment]
I think only @huan could review this PR.

**Comment by huan** [comment]
Thanks for pinging me.

Will review it later, thanks to all @iamrajiv @rohi
@lijia

**Comment by huan** [comment]
It's a great feature and I'm working on it this week.

**Pull request closed without merging**
