### PR TITLE
[GSoD 2021] Added issue and pull request templates 

### PR DESCRIPTION
**Pull request by iamrajiv**
Related: wechaty/docusaurus#1012

Screenshot 2021-07-05 at 9 51 08 PM
Screenshot 2021-07-02 at 10 59 04 AM
Screenshot 2021-07-02 at 10 59 13 AM
Screenshot 2021-07-02 at 10 59 24 AM

### CODE REVIEW

**Comment by iamrajiv** [comment]
@proudofsimin @Rohitesh-Kumar-Jain Please take a look.

**Review by Rohitesh-Kumar-Jain — APPROVED** [review]
LGTM, I am not sure though they needed this template

**Comment by iamrajiv** [comment]
@Rohitesh-Kumar-Jain see this https://github.com/wechaty/wechaty.js.org/issues/1012#issuecomment-882695556

**Comment by iamrajiv** [comment]
@simin plz take a look.

**Review by huan — APPROVED** [review]
LGTM

**Comment by huan** [comment]
Thank you very much for the improvement!

**Pull request merged**
