### PR TITLE
[GSoD 2021] Refactored README.md

### PR DESCRIPTION
**Pull request by iamrajiv**
Related: wechaty/docusaurus#1012

Screenshot 2021-07-11 at 6 57 41 AM
Screenshot 2021-07-11 at 6 57 57 AM
Screenshot 2021-07-11 at 6 58 06 AM
Screenshot 2021-07-11 at 6 58 38 AM

### CODE REVIEW

**Comment by iamrajiv** [comment]
@huan @proudofsimin @Rohitesh-Kumar-Jain Please take a look.

**Review by proudofsimin — APPROVED** [review]
I like your updated version :)

**Comment by Rohitesh-Kumar-Jain** [comment]
Thank you for the refactoring

**Review by Rohitesh-Kumar-Jain — APPROVED** [review]

**Comment by iamrajiv** [comment]
@lijiarui please take a look.

**Comment by iamrajiv** [comment]
@lijiarui please take a look.

**Comment by iamrajiv** [comment]
@huan Can you take a look?

**Review by huan — CHANGES_REQUESTED** [review]
LGTM, except that we need to keep the `/docs/` folder unchanged.

Please put all `assets/images/*` to `docs/images/` and then we are good to merge this PR.

Thank you very much!

**Comment by iamrajiv** [comment]
@huan done the requested changes.

**Comment by iamrajiv** [comment]
@huan Done with the requested changes. Also, NPM/ Build is failing because of PR #17 but I think we can ignore this.

**Review by huan — APPROVED** [review]
LGTM

Thank you very much for update the README to this beautiful new version!

**Pull request merged**
